package main

type Config struct {
	Methods []MethodInfo
}
type MethodInfo struct {
	Name string
	Path string
}

var fieldTemplate = `# Code generated by protoc-gen-api-config. DO NOT EDIT.
type: google.api.Service
config_version: 3

http:
  rules:
    {{ range .Methods }}- selector: {{ .Name }}
      post: {{ .Path }}
      body: "*"
    {{ end }}
`
